=== bitsnorge/e-tinglysing-afpant/spesifikasjoner/afpant/afpant-kjøperspantedokument/afpant-forutsetningsbrev/afpant-forutsetningsbrev.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Forutsetningsbrev" nillable="false" type="Forutsetningsbrev"/>
  <xs:complexType name="Forutsetningsbrev">
    <xs:annotation>
        <xs:documentation>Denne klassen skal benyttes for å produsere et strukturert forutsetningsbrev fra kreditor (bank) til eiendomsmegler. 
Forutsetningsbrevet sendes sammen med ett pantedokument, og det må inneholde informasjon om pantedokumentet som overføres, forventet prioritet, forutsetninger for overførselen, samt beløp som overføres.
Informasjon om innbetalingen (beløp, totalbeløp, mottakerkontonummer og kid) benyttes av mottaker til blant annet etterlevelse av hvitvaskingsreglement.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Kreditor" type="RettighetsHaver">
          <xs:annotation>
              <xs:documentation>Rettighetshaver/kreditor</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="Debitorer" type="ArrayOfRettighetsHaver" />
      <xs:element minOccurs="1" maxOccurs="1" name="Registerenheter" type="ArrayOfRegisterenhet" />
      <xs:element minOccurs="1" maxOccurs="1" name="PantedokumentDetaljer" type="Pantedokument" />
      <xs:element minOccurs="1" maxOccurs="1" name="OverfoerselDetaljer" type="Overfoersel" />
      <xs:element minOccurs="1" maxOccurs="1" name="Avsender" type="Person">
          <xs:annotation>
              <xs:documentation>Saksbehandler i bank/depot. Kontaktinformasjon er viktig for mottaker (oppgjørsmedarbeider) i tilfelle prioritetskollisjon eller andre mangler i oversendt pantedokument må avklares.</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="Mottaker" type="JuridiskPerson" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RettighetsHaver">
    <xs:annotation>
        <xs:documentation>Kan brukes for å beskrive en rettighetshaver som enten er en privatperson med fødselsnummer, eller en organisasjon med organisasjonsnummer.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Nummer" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="Navn" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfRettighetsHaver">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="RettighetsHaver" nillable="true" type="RettighetsHaver" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfRegisterenhet">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="Registerenhet" nillable="true" type="Registerenhet" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Registerenhet">
    <xs:annotation>
        <xs:documentation>Representerer enten fast eiendom (inkl feste eller seksjonsnummer) eller en borettsandel. </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="KommuneNavn" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Kommunenummer" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Gardsnummer" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Bruksnummer" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Festenummer" type="xs:string" default="0">
          <xs:annotation>
              <xs:documentation>Angi "0" dersom fast eiendom og feste ikke er relevant</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="Seksjonsnummer" type="xs:string" default="0">
          <xs:annotation>
              <xs:documentation>Angi "0" dersom useksjonert fast eiendom</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="Organisasjonsnummer" type="xs:string">
          <xs:annotation>
              <xs:documentation>Borettslagets organisasjonsnummer</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="Andelsnummer" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="BorettslagNavn" type="xs:string">
          <xs:annotation>
              <xs:documentation>Angi navn på borettslaget dersom dette er tilgjengelig</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="Adresse" type="xs:string">
          <xs:annotation>
              <xs:documentation>Angi eiendommens gateadresse dersom dette er tilgjengelig</xs:documentation>
          </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Pantedokument">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Beloep" type="xs:double">
          <xs:annotation>
              <xs:documentation>Pålydende beløp på pantedokumentet som overføres</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="ForstePrioritet" type="xs:boolean">
          <xs:annotation>
              <xs:documentation>Angi som true dersom man skal ha første prioritet. XSLT vil i så fall ignorere eventuelt innhold i Pantedokument.Prioritet-listen.</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="Prioritet" type="ArrayOfPrioritetsAngivelse">
          <xs:annotation>
              <xs:documentation>Angi ett item for hvert av pantene det skal vikes for eller sidestilles med.</xs:documentation>
          </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfPrioritetsAngivelse">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="PrioritetsAngivelse" nillable="true" type="PrioritetsAngivelse" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PrioritetsAngivelse">
    <xs:annotation>
        <xs:documentation>Angir detaljer om et annet pant som påvirker prioriteten.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Rekkefolge" type="PrioritetsRekkefolge" />
      <xs:element minOccurs="1" maxOccurs="1" name="Panthaver" type="RettighetsHaver">
          <xs:annotation>
              <xs:documentation>Panthaver kan være enten privatperson eller organisasjon.</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="Beloep" type="xs:double" />
      <xs:element minOccurs="0" maxOccurs="1" name="PrioritetsBeskrivelse" type="xs:string" nillable="true">
          <xs:annotation>
              <xs:documentation>Tekstlig representasjon av forventet prioritet (1. pri, likestilt med, viker for kreditor xxx)</xs:documentation>
          </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="PrioritetsRekkefolge">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PrioritetEtter" />
      <xs:enumeration value="PrioritetLikestiltMed" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Overfoersel">
    <xs:annotation>
      <xs:documentation>Overføringsdetaljer. Kan ikke angi både KID og betalingsmelding.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Beloep" type="xs:double">
          <xs:annotation>
              <xs:documentation>Beløpet som overføres sammen med pantedokumentet (kan være mindre enn totalbeløpet)</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="BeloepOverforesDato" type="xs:date">
          <xs:annotation>
              <xs:documentation>En dato som indikerer når beløpet angitt i Beloep blir overført til mottakers kontonummer</xs:documentation>
          </xs:annotation>
      </xs:element>           
      <xs:element minOccurs="1" maxOccurs="1" name="TotalBeloep" type="xs:double">
          <xs:annotation>
              <xs:documentation>Totalt beløp som skal innbetales i henhold til kjøpekontrakt</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="TilKontonummer" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="KID" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Betalingsmelding" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="KreditorSaksnummer" type="xs:string">
          <xs:annotation>
              <xs:documentation>Kan angi f.eks lånesaksnummer eller referanse i (bank)fagsystem</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="MeglerSaksnummer" type="xs:string">
          <xs:annotation>
              <xs:documentation>Kan angi meglers oppdragsnummer dersom dette er tilgjengelig</xs:documentation>
          </xs:annotation>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="ProdusertDato" type="xs:dateTime">
          <xs:annotation>
              <xs:documentation>En timestamp som indikerer når forutsetningsbrevet ble produsert/overført</xs:documentation>
          </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfString">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Person">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Navn" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Email" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="TelefonDirekte" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Telefon" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="JuridiskPerson">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Navn" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Organisasjonsnummer" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== bitsnorge/e-tinglysing-afpant/spesifikasjoner/afpant/afpant-kjøperspantedokument/afpant-forutsetningsbrev/afpant-forutsetningsbrev-eksempel_betalingsmelding.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="./afpant-forutsetningsbrev.xslt"?>
<Forutsetningsbrev xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xsi:noNamespaceSchemaLocation="./afpant-forutsetningsbrev.xsd">
  <Kreditor>
    <Nummer>123456789</Nummer>
    <Navn>TietoEVRY Banken, filial Fornebu</Navn>
  </Kreditor>
  <Debitorer>
    <RettighetsHaver>
      <Nummer>01234567890</Nummer>
      <Navn>Donald Duck</Navn>
    </RettighetsHaver>
    <RettighetsHaver>
      <Nummer>01234567890</Nummer>
      <Navn>Dolly Duck</Navn>
    </RettighetsHaver>
  </Debitorer>
  <Registerenheter>
    <Registerenhet>
      <KommuneNavn>Bergen</KommuneNavn>
      <Kommunenummer>4601</Kommunenummer>
      <Gardsnummer>10</Gardsnummer>
      <Bruksnummer>818</Bruksnummer>
      <Seksjonsnummer>41</Seksjonsnummer>
    </Registerenhet>
  </Registerenheter>
  <PantedokumentDetaljer>
    <Beloep>251230</Beloep>
    <ForstePrioritet>false</ForstePrioritet>
    <Prioritet>
      <PrioritetsAngivelse>
        <Rekkefolge>PrioritetEtter</Rekkefolge>
        <Panthaver>
          <Nummer>987412548</Nummer>
          <Navn>Husbanken</Navn>
        </Panthaver>
        <Beloep>1250000</Beloep>
        <PrioritetsBeskrivelse>Tekst av noe slag</PrioritetsBeskrivelse>
      </PrioritetsAngivelse>
      <PrioritetsAngivelse>
        <Rekkefolge>PrioritetLikestiltMed</Rekkefolge>
        <Panthaver>
          <Nummer>921345687</Nummer>
          <Navn>Sparebanken Vest</Navn>
        </Panthaver>
        <Beloep>2000000</Beloep>
        <PrioritetsBeskrivelse>Bank til annet familie medlem</PrioritetsBeskrivelse>
      </PrioritetsAngivelse>
    </Prioritet>
  </PantedokumentDetaljer>
  <OverfoerselDetaljer>
    <Beloep>2100000</Beloep>
    <BeloepOverforesDato>2019-01-23</BeloepOverforesDato>
    <TotalBeloep>2500000</TotalBeloep>
    <TilKontonummer>65501100000</TilKontonummer>
    <Betalingsmelding>Merk innbetaling med: AF123M7</Betalingsmelding>
    <KreditorSaksnummer>Lånesak 124-221/22</KreditorSaksnummer>
    <MeglerSaksnummer>117-00-1002 Lånegaten 15 B</MeglerSaksnummer>
    <BeloepGjelder>dekning av kjøpesum for ovennevnte eiendom</BeloepGjelder>
    <ProdusertDato>2019-01-25T10:15:23.2962746+01:00</ProdusertDato>
  </OverfoerselDetaljer>
  <Avsender>
    <Navn>Bjarne Bankrådgiver</Navn>
    <Email>bjarne.bank@nordea-afpant.com</Email>
    <TelefonDirekte>80000000</TelefonDirekte>
    <Telefon>23206001</Telefon>
  </Avsender>
  <Mottaker>
    <Navn>Oppgjørsforetaket AS</Navn>
    <Organisasjonsnummer>800000000</Organisasjonsnummer>
  </Mottaker>
</Forutsetningsbrev>
